export const FORMULARIO_PROJETO = 'PROJETO_PROJETO'
export const OBTER_PROJETOS = 'OBTER_PROJETOS'
export const ADICIONAR_PROJETO = 'ADICIONAR_PROJETO'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO'
export const PROJETO_ATUAL = 'PROJETO_ATUAL'
export const ELIMINAR_PROJETO = 'ELIMINAR_PROJETO'

export const TAREFAS_PROJETO = 'TAREFAS_PROJETO'
export const ADICIONAR_TAREFA = 'ADICIONAR_TAREFA'

export const VALIDAR_TAREFA = 'VALIDAR_TAREFA'